### ISSUE TITLE
Managing your board for the first time throws an error

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#128]
After a fresh jschan install, having created your board when you click 'Manage' for the first time you get an Internal Server Error. It only happens once.
PM2 chan logs say this:
```
Cannot read property 'length' of undefined
    at eval (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2551:32)
    at eval (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2570:4)
    at template (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2677:180)
    at Object.exports.renderFile (/home/jschan/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/jschan/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/home/jschan/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/jschan/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/jschan/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/jschan/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/jschan/node_modules/express/lib/response.js:1012:7)
    at module.exports (/home/jschan/models/pages/manage/settings.js:9:3)
    at Layer.handle [as handle_request] (/home/jschan/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jschan/node_modules/express/lib/router/route.js:137:13)
    at csrf (/home/jschan/node_modules/csurf/index.js:117:5)
    at Layer.handle [as handle_request] (/home/jschan/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jschan/node_modules/express/lib/router/route.js:137:13) {
  path: '/home/jschan/views/includes/2charisocountries.pug'
}

```

**Comment by fatchan** [comment]
Updated the boardDefaults when a board is created, it was missing a new property.

If you had not already, make sure to run `gulp migrate`. The existing board settings page might still be broken. If so, you will have to run the following commands in mongo console to fix the database.
```
use jschan
db.boards.updateMany({}, { '$set': { 'settings.blockedCountries': [] } })
```
