### ISSUE TITLE
Settings page internal error

### ISSUE THREAD

**Issue by godhandgriffith** [fatchan/jschan#132]
I tried gulp migrate and manually fixing tables like mentioned. It didn't help. 

```
1|chan     |     at Object.exports.renderFile (/var/www/yakuchan.club/html/node_modules/pug/lib/index.js:427:38)
1|chan     |     at Object.exports.renderFile (/var/www/yakuchan.club/html/node_modules/pug/lib/index.js:417:21)
1|chan     |     at View.exports.__express [as engine] (/var/www/yakuchan.club/html/node_modules/pug/lib/index.js:4
64:11)
1|chan     |     at View.render (/var/www/yakuchan.club/html/node_modules/express/lib/view.js:135:8)
1|chan     |     at tryRender (/var/www/yakuchan.club/html/node_modules/express/lib/application.js:640:10)
1|chan     |     at Function.render (/var/www/yakuchan.club/html/node_modules/express/lib/application.js:592:3)
1|chan     |     at ServerResponse.render (/var/www/yakuchan.club/html/node_modules/express/lib/response.js:1012:7)
1|chan     |     at module.exports (/var/www/yakuchan.club/html/models/pages/manage/settings.js:9:3)
1|chan     |     at Layer.handle [as handle_request] (/var/www/yakuchan.club/html/node_modules/express/lib/router/l
ayer.js:95:5)
1|chan     |     at next (/var/www/yakuchan.club/html/node_modules/express/lib/router/route.js:137:13)
1|chan     |     at csrf (/var/www/yakuchan.club/html/node_modules/csurf/index.js:117:5)
1|chan     |     at Layer.handle [as handle_request] (/var/www/yakuchan.club/html/node_modules/express/lib/router/l
ayer.js:95:5)
1|chan     |     at next (/var/www/yakuchan.club/html/node_modules/express/lib/router/route.js:137:13) {
1|chan     |   path: '/var/www/yakuchan.club/html/views/includes/2charisocountries.pug'
1|chan     | }
```

**Comment by fatchan** [comment]
Make sure you update your config to match https://github.com/fatchan/jschan/commit/81cae2c005b63301e389f341430c6dfe980b8ebc and also run `gulp cache` as you could have the board still cached, even if you edited the table in the database. Close the issue if it solves please :+1:

**Comment by godhandgriffith** [comment]
Worked like a charm! Thank you.
