### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#161]
Happens with both `managelogs.pug` and `/mixins/ban.pug`.

```
2020-06-05 11:19:08.604: TypeError: /home/jschan/views/mixins/ban.pug:13
    11| 				| Global
    12| 		td= ban.reason
  > 13| 		- const ip = permLevel > ipHashPermLevel ? ban.ip.single.slice(-10) : ban.ip.raw;
    14| 		td #{ip}
    15| 		td #{ban.type}
    16| 		td #{ban.issuer}

Cannot read property 'slice' of undefined
    at Object.pug_interp [as ban] (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:695:56)
    at eval (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:1152:18)
    at eval (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:1163:4)
    at template (eval at wrap (/home/jschan/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:1214:180)
    at Object.exports.renderFile (/home/jschan/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/jschan/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/home/jschan/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/jschan/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/jschan/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/jschan/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/jschan/node_modules/express/lib/response.js:1012:7)
    at module.exports (/home/jschan/models/pages/manage/bans.js:16:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  path: '/home/jschan/views/mixins/ban.pug'
}
```

**Comment by fatchan** [comment]
I'm pretty sure you run dev branch, did you run `gulp migrate` after pulling changes recently? Make a database backup beforehand because it makes a lot of changes. 

If the issue persists after that, post a document from your bans and modlogs collection (with identifying info redacted ofc).

**Comment by hawkoon** [comment]
Ah I see, I had no idea that was required. I was still on 0.0.6, now on 0.0.9. Will keep an eye on the logs.

**Comment by fatchan** [comment]
:+1: 
Yeah you should check that after every update. I'll add a check to the startup of each of the processes to make sure the db version is up-do-date and if not, exit. 

I say "if the issue persists" and suggested a backup because if you ran it on an old db version and documents with the new schema were already created it could cause issues and require manually fixing whatever is messed up in the db. Pain in the ass to do.
